
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.wilsoncys.compi1.java.model.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int BOOL = 3;
  public static final int REAL = 80;
  public static final int CONST = 54;
  public static final int PAR_CL = 46;
  public static final int SCAN = 95;
  public static final int PAR_OP = 45;
  public static final int UNTIL = 76;
  public static final int INP_INT = 68;
  public static final int G_EQUALS = 16;
  public static final int ASSIGNMENT = 20;
  public static final int CHARAC = 4;
  public static final int DIVIDED = 11;
  public static final int DOUBLE = 40;
  public static final int RAISED = 12;
  public static final int PROTECTED = 59;
  public static final int NOT = 32;
  public static final int ARRAY = 74;
  public static final int DIFFERENT = 19;
  public static final int BRACK_R = 52;
  public static final int PASCAL = 82;
  public static final int VAR = 53;
  public static final int THEN = 72;
  public static final int UNEGATIVE = 33;
  public static final int JAVATODO = 89;
  public static final int BRACK_L = 51;
  public static final int PRINTLN = 66;
  public static final int PASCALSIMP = 88;
  public static final int MOD = 13;
  public static final int CLASS = 65;
  public static final int INCLUDE = 90;
  public static final int CLRSCR = 97;
  public static final int ENTERO = 5;
  public static final int PLUS = 8;
  public static final int L_EQUALS = 17;
  public static final int WHILE = 27;
  public static final int PASCALUNO = 86;
  public static final int EXTENDS = 62;
  public static final int DECIMAL = 6;
  public static final int CHAR = 42;
  public static final int BOOLEAN = 41;
  public static final int GETCH = 85;
  public static final int SWITCH = 26;
  public static final int SEMIC = 49;
  public static final int DO = 21;
  public static final int FOR = 24;
  public static final int GREATER = 14;
  public static final int VOID = 44;
  public static final int PUBLIC = 61;
  public static final int RETURN = 58;
  public static final int READLN = 78;
  public static final int ELSE = 23;
  public static final int JAVA = 83;
  public static final int BREAK = 25;
  public static final int DOT = 57;
  public static final int PROCEDURE = 70;
  public static final int INT = 39;
  public static final int NULL = 37;
  public static final int EOF = 0;
  public static final int THIS = 63;
  public static final int DEFAULT = 29;
  public static final int FUNCTION = 81;
  public static final int PRINT = 38;
  public static final int MASK_S = 94;
  public static final int REPEAT = 71;
  public static final int JAVAUNO = 87;
  public static final int K_CL = 48;
  public static final int MAIN = 64;
  public static final int MINUS = 9;
  public static final int K_OP = 47;
  public static final int OR = 30;
  public static final int error = 1;
  public static final int MASK_F = 93;
  public static final int MASK_D = 91;
  public static final int MASK_C = 92;
  public static final int ANDSIMPLE = 96;
  public static final int CONTINUE = 28;
  public static final int IF = 22;
  public static final int ID = 7;
  public static final int MINUSMINUS = 36;
  public static final int OF = 79;
  public static final int END = 77;
  public static final int COLON = 55;
  public static final int CASE = 84;
  public static final int BEGIN = 75;
  public static final int PLUSPLUS = 35;
  public static final int CADENA = 2;
  public static final int NEW = 56;
  public static final int STRING = 43;
  public static final int LESS = 15;
  public static final int AND = 31;
  public static final int PRIVATE = 60;
  public static final int TO = 73;
  public static final int POINTS = 50;
  public static final int UMINUS = 34;
  public static final int EQUALS = 18;
  public static final int INP_F = 69;
  public static final int INP_C = 67;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "BOOL",
  "CHARAC",
  "ENTERO",
  "DECIMAL",
  "ID",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDED",
  "RAISED",
  "MOD",
  "GREATER",
  "LESS",
  "G_EQUALS",
  "L_EQUALS",
  "EQUALS",
  "DIFFERENT",
  "ASSIGNMENT",
  "DO",
  "IF",
  "ELSE",
  "FOR",
  "BREAK",
  "SWITCH",
  "WHILE",
  "CONTINUE",
  "DEFAULT",
  "OR",
  "AND",
  "NOT",
  "UNEGATIVE",
  "UMINUS",
  "PLUSPLUS",
  "MINUSMINUS",
  "NULL",
  "PRINT",
  "INT",
  "DOUBLE",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "VOID",
  "PAR_OP",
  "PAR_CL",
  "K_OP",
  "K_CL",
  "SEMIC",
  "POINTS",
  "BRACK_L",
  "BRACK_R",
  "VAR",
  "CONST",
  "COLON",
  "NEW",
  "DOT",
  "RETURN",
  "PROTECTED",
  "PRIVATE",
  "PUBLIC",
  "EXTENDS",
  "THIS",
  "MAIN",
  "CLASS",
  "PRINTLN",
  "INP_C",
  "INP_INT",
  "INP_F",
  "PROCEDURE",
  "REPEAT",
  "THEN",
  "TO",
  "ARRAY",
  "BEGIN",
  "UNTIL",
  "END",
  "READLN",
  "OF",
  "REAL",
  "FUNCTION",
  "PASCAL",
  "JAVA",
  "CASE",
  "GETCH",
  "PASCALUNO",
  "JAVAUNO",
  "PASCALSIMP",
  "JAVATODO",
  "INCLUDE",
  "MASK_D",
  "MASK_C",
  "MASK_F",
  "MASK_S",
  "SCAN",
  "ANDSIMPLE",
  "CLRSCR"
  };
}

