// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexico.jflex

package com.wilsoncys.compi1.javacraft.model.analisis;


// importaciones
import java_cup.runtime.Symbol;
import java.util.LinkedList;
import com.wilsoncys.compi1.javacraft.model.excepciones.Errores;



@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  1,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  0,  0,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 19, 20, 21, 22,  0, 
     0, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 
    38, 32, 39, 40, 41, 42, 43, 44, 45, 32, 32, 46, 47, 48, 49, 50, 
     0, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 
    38, 32, 39, 40, 41, 42, 43, 44, 45, 32, 32, 51, 52, 53,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\21\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\1\1\31\1\32\1\0\1\33"+
    "\1\0\1\34\2\0\1\35\1\36\1\37\1\0\1\2"+
    "\1\0\1\40\1\41\1\42\1\43\6\23\1\44\5\23"+
    "\1\45\20\23\1\46\2\47\1\0\1\50\13\23\1\51"+
    "\1\52\4\23\1\53\13\23\1\54\2\23\1\2\1\23"+
    "\1\55\1\23\1\56\4\23\1\57\1\23\1\60\1\23"+
    "\1\61\1\62\13\23\1\63\1\23\1\64\1\65\2\23"+
    "\1\66\1\67\1\70\4\23\1\71\1\72\5\23\1\73"+
    "\4\23\1\74\1\75\1\23\1\76\1\23\1\77\3\23"+
    "\1\100\1\101\1\102\1\23\1\103\1\104\2\23\1\105"+
    "\1\106\1\107\3\23\1\110\2\23\1\111\1\112\1\23"+
    "\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\66\0\u010e\0\u0144"+
    "\0\66\0\66\0\u017a\0\u01b0\0\66\0\u01e6\0\66\0\u021c"+
    "\0\u0252\0\66\0\66\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360"+
    "\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510"+
    "\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\u0654\0\u068a\0\66"+
    "\0\66\0\66\0\66\0\66\0\u06c0\0\66\0\66\0\330"+
    "\0\66\0\u06f6\0\66\0\u072c\0\u0762\0\66\0\66\0\66"+
    "\0\u0798\0\u07ce\0\u0804\0\66\0\66\0\66\0\66\0\u083a"+
    "\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea"+
    "\0\u0a20\0\u0a56\0\u0a8c\0\u046e\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64"+
    "\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde\0\u0d14"+
    "\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\66\0\66\0\u072c\0\u0e22"+
    "\0\u0804\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0f9c"+
    "\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u046e\0\u046e\0\u10aa\0\u10e0"+
    "\0\u1116\0\u114c\0\u046e\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a"+
    "\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368\0\u139e\0\u046e\0\u13d4"+
    "\0\u140a\0\66\0\u1440\0\u046e\0\u1476\0\u046e\0\u14ac\0\u14e2"+
    "\0\u1518\0\u154e\0\u046e\0\u1584\0\u046e\0\u15ba\0\u046e\0\u046e"+
    "\0\u15f0\0\u1626\0\u165c\0\u1692\0\u16c8\0\u16fe\0\u1734\0\u176a"+
    "\0\u17a0\0\u17d6\0\u180c\0\u046e\0\u1842\0\u046e\0\u046e\0\u1878"+
    "\0\u18ae\0\u046e\0\u046e\0\u046e\0\u18e4\0\u191a\0\u1950\0\u1986"+
    "\0\u046e\0\u19bc\0\u19f2\0\u1a28\0\u1a5e\0\u1a94\0\u1aca\0\u046e"+
    "\0\u1b00\0\u1b36\0\u1b6c\0\u1ba2\0\u046e\0\u046e\0\u1bd8\0\u046e"+
    "\0\u1c0e\0\u046e\0\u1c44\0\u1c7a\0\u1cb0\0\u046e\0\u046e\0\u046e"+
    "\0\u1ce6\0\u046e\0\u046e\0\u1d1c\0\u1d52\0\u046e\0\u046e\0\u046e"+
    "\0\u1d88\0\u1dbe\0\u1df4\0\u046e\0\u1e2a\0\u1e60\0\u046e\0\u046e"+
    "\0\u1e96\0\u046e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\2\35\1\36\2\35\1\37"+
    "\1\40\1\41\1\35\1\42\1\43\1\44\1\45\1\35"+
    "\1\46\1\47\1\35\1\50\1\2\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\67\0\2\3\110\0\1\57\40\0"+
    "\5\60\1\61\51\60\1\62\6\60\7\0\1\63\56\0"+
    "\10\64\1\0\46\64\1\65\6\64\13\0\1\66\66\0"+
    "\1\67\67\0\1\70\62\0\1\71\4\0\1\72\64\0"+
    "\1\73\1\0\1\21\71\0\1\74\65\0\1\75\1\76"+
    "\64\0\1\77\61\0\1\35\5\0\17\35\1\100\7\35"+
    "\4\0\1\35\24\0\1\35\5\0\16\35\1\101\1\35"+
    "\1\102\6\35\4\0\1\35\24\0\1\35\5\0\7\35"+
    "\1\103\3\35\1\104\2\35\1\105\10\35\4\0\1\35"+
    "\24\0\1\35\5\0\16\35\1\106\10\35\4\0\1\35"+
    "\24\0\1\35\5\0\13\35\1\107\12\35\1\110\4\0"+
    "\1\35\24\0\1\35\5\0\1\111\7\35\1\112\5\35"+
    "\1\113\10\35\4\0\1\35\24\0\1\35\5\0\27\35"+
    "\4\0\1\35\24\0\1\35\5\0\5\35\1\114\7\35"+
    "\1\115\11\35\4\0\1\35\24\0\1\35\5\0\4\35"+
    "\1\116\3\35\1\117\16\35\4\0\1\35\24\0\1\35"+
    "\5\0\1\120\26\35\4\0\1\35\24\0\1\35\5\0"+
    "\4\35\1\121\22\35\4\0\1\35\24\0\1\35\5\0"+
    "\20\35\1\122\2\35\1\123\3\35\4\0\1\35\24\0"+
    "\1\35\5\0\4\35\1\124\11\35\1\125\10\35\4\0"+
    "\1\35\24\0\1\35\5\0\22\35\1\126\4\35\4\0"+
    "\1\35\24\0\1\35\5\0\7\35\1\127\6\35\1\130"+
    "\1\35\1\131\6\35\4\0\1\35\24\0\1\35\5\0"+
    "\1\132\15\35\1\133\10\35\4\0\1\35\24\0\1\35"+
    "\5\0\7\35\1\134\17\35\4\0\1\35\67\0\1\135"+
    "\6\0\1\60\2\0\1\60\33\0\1\60\4\0\1\60"+
    "\5\0\1\60\16\0\1\136\65\0\1\137\33\0\1\64"+
    "\2\0\1\64\1\0\1\64\5\0\1\64\6\0\13\71"+
    "\1\140\52\71\2\72\1\0\63\72\21\0\1\141\65\0"+
    "\1\35\5\0\17\35\1\142\7\35\4\0\1\35\24\0"+
    "\1\35\5\0\16\35\1\143\10\35\4\0\1\35\24\0"+
    "\1\35\5\0\4\35\1\144\22\35\4\0\1\35\24\0"+
    "\1\35\5\0\1\145\26\35\4\0\1\35\24\0\1\35"+
    "\5\0\1\146\26\35\4\0\1\35\24\0\1\35\5\0"+
    "\15\35\1\147\11\35\4\0\1\35\24\0\1\35\5\0"+
    "\23\35\1\150\3\35\4\0\1\35\24\0\1\35\5\0"+
    "\21\35\1\151\5\35\4\0\1\35\24\0\1\35\5\0"+
    "\22\35\1\152\4\35\4\0\1\35\24\0\1\35\5\0"+
    "\13\35\1\153\13\35\4\0\1\35\24\0\1\35\5\0"+
    "\15\35\1\154\11\35\4\0\1\35\24\0\1\35\5\0"+
    "\20\35\1\155\6\35\4\0\1\35\24\0\1\35\5\0"+
    "\22\35\1\156\4\35\4\0\1\35\24\0\1\35\5\0"+
    "\15\35\1\157\11\35\4\0\1\35\24\0\1\35\5\0"+
    "\21\35\1\160\5\35\4\0\1\35\24\0\1\35\5\0"+
    "\10\35\1\161\11\35\1\162\4\35\4\0\1\35\24\0"+
    "\1\35\5\0\25\35\1\163\1\35\4\0\1\35\24\0"+
    "\1\35\5\0\10\35\1\164\5\35\1\165\10\35\4\0"+
    "\1\35\24\0\1\35\5\0\1\35\1\166\25\35\4\0"+
    "\1\35\24\0\1\35\5\0\14\35\1\167\5\35\1\170"+
    "\4\35\4\0\1\35\24\0\1\35\5\0\23\35\1\171"+
    "\3\35\4\0\1\35\24\0\1\35\5\0\1\172\17\35"+
    "\1\173\6\35\4\0\1\35\24\0\1\35\5\0\10\35"+
    "\1\174\16\35\4\0\1\35\24\0\1\35\5\0\21\35"+
    "\1\175\5\35\4\0\1\35\24\0\1\35\5\0\23\35"+
    "\1\176\3\35\4\0\1\35\24\0\1\35\5\0\20\35"+
    "\1\177\6\35\4\0\1\35\24\0\1\35\5\0\10\35"+
    "\1\200\16\35\4\0\1\35\24\0\1\35\5\0\10\35"+
    "\1\201\16\35\4\0\1\35\3\0\13\71\1\140\4\71"+
    "\1\202\45\71\21\0\1\35\5\0\4\35\1\203\22\35"+
    "\4\0\1\35\24\0\1\35\5\0\13\35\1\204\13\35"+
    "\4\0\1\35\24\0\1\35\5\0\1\205\26\35\4\0"+
    "\1\35\24\0\1\35\5\0\20\35\1\206\6\35\4\0"+
    "\1\35\24\0\1\35\5\0\21\35\1\207\5\35\4\0"+
    "\1\35\24\0\1\35\5\0\21\35\1\210\1\211\4\35"+
    "\4\0\1\35\24\0\1\35\5\0\1\35\1\212\25\35"+
    "\4\0\1\35\24\0\1\35\5\0\4\35\1\213\22\35"+
    "\4\0\1\35\24\0\1\35\5\0\4\35\1\214\22\35"+
    "\4\0\1\35\24\0\1\35\5\0\21\35\1\176\5\35"+
    "\4\0\1\35\24\0\1\35\5\0\3\35\1\215\23\35"+
    "\4\0\1\35\24\0\1\35\5\0\6\35\1\216\20\35"+
    "\4\0\1\35\24\0\1\35\5\0\22\35\1\217\4\35"+
    "\4\0\1\35\24\0\1\35\5\0\15\35\1\220\11\35"+
    "\4\0\1\35\24\0\1\35\5\0\2\35\1\221\24\35"+
    "\4\0\1\35\24\0\1\35\5\0\15\35\1\222\6\35"+
    "\1\223\2\35\4\0\1\35\24\0\1\35\5\0\22\35"+
    "\1\224\4\35\4\0\1\35\24\0\1\35\5\0\13\35"+
    "\1\225\13\35\4\0\1\35\24\0\1\35\5\0\16\35"+
    "\1\226\10\35\4\0\1\35\24\0\1\35\5\0\23\35"+
    "\1\227\3\35\4\0\1\35\24\0\1\35\5\0\15\35"+
    "\1\230\11\35\4\0\1\35\24\0\1\35\5\0\20\35"+
    "\1\231\6\35\4\0\1\35\24\0\1\35\5\0\10\35"+
    "\1\232\12\35\1\233\3\35\4\0\1\35\24\0\1\35"+
    "\5\0\21\35\1\234\5\35\4\0\1\35\24\0\1\35"+
    "\5\0\22\35\1\235\4\35\4\0\1\35\24\0\1\35"+
    "\5\0\4\35\1\236\22\35\4\0\1\35\24\0\1\35"+
    "\5\0\3\35\1\237\23\35\4\0\1\35\24\0\1\35"+
    "\5\0\13\35\1\240\13\35\4\0\1\35\24\0\1\35"+
    "\5\0\15\35\1\241\11\35\4\0\1\35\24\0\1\35"+
    "\5\0\12\35\1\242\14\35\4\0\1\35\24\0\1\35"+
    "\5\0\21\35\1\243\5\35\4\0\1\35\24\0\1\35"+
    "\5\0\22\35\1\244\4\35\4\0\1\35\24\0\1\35"+
    "\5\0\10\35\1\245\16\35\4\0\1\35\24\0\1\35"+
    "\5\0\13\35\1\246\13\35\4\0\1\35\24\0\1\35"+
    "\5\0\15\35\1\247\11\35\4\0\1\35\24\0\1\35"+
    "\5\0\22\35\1\250\4\35\4\0\1\35\24\0\1\35"+
    "\5\0\7\35\1\251\17\35\4\0\1\35\24\0\1\35"+
    "\5\0\22\35\1\252\4\35\4\0\1\35\24\0\1\35"+
    "\5\0\1\253\26\35\4\0\1\35\24\0\1\35\5\0"+
    "\4\35\1\254\22\35\4\0\1\35\24\0\1\35\5\0"+
    "\10\35\1\255\16\35\4\0\1\35\24\0\1\35\5\0"+
    "\24\35\1\256\2\35\4\0\1\35\24\0\1\35\5\0"+
    "\20\35\1\257\6\35\4\0\1\35\24\0\1\35\5\0"+
    "\3\35\1\260\23\35\4\0\1\35\24\0\1\35\5\0"+
    "\22\35\1\261\4\35\4\0\1\35\24\0\1\35\5\0"+
    "\15\35\1\262\11\35\4\0\1\35\24\0\1\35\5\0"+
    "\2\35\1\263\24\35\4\0\1\35\24\0\1\35\5\0"+
    "\20\35\1\264\6\35\4\0\1\35\24\0\1\35\5\0"+
    "\4\35\1\265\22\35\4\0\1\35\24\0\1\35\5\0"+
    "\3\35\1\266\23\35\4\0\1\35\24\0\1\35\5\0"+
    "\15\35\1\267\11\35\4\0\1\35\24\0\1\35\5\0"+
    "\4\35\1\270\22\35\4\0\1\35\24\0\1\35\5\0"+
    "\3\35\1\271\23\35\4\0\1\35\24\0\1\35\5\0"+
    "\7\35\1\272\17\35\4\0\1\35\24\0\1\35\5\0"+
    "\13\35\1\273\13\35\4\0\1\35\24\0\1\35\5\0"+
    "\22\35\1\274\4\35\4\0\1\35\24\0\1\35\5\0"+
    "\2\35\1\275\24\35\4\0\1\35\24\0\1\35\5\0"+
    "\2\35\1\276\24\35\4\0\1\35\24\0\1\35\5\0"+
    "\4\35\1\277\22\35\4\0\1\35\24\0\1\35\5\0"+
    "\15\35\1\300\11\35\4\0\1\35\24\0\1\35\5\0"+
    "\27\35\4\0\1\301\24\0\1\35\5\0\6\35\1\302"+
    "\20\35\4\0\1\35\24\0\1\35\5\0\22\35\1\303"+
    "\4\35\4\0\1\35\24\0\1\35\5\0\10\35\1\304"+
    "\16\35\4\0\1\35\24\0\1\35\5\0\23\35\1\305"+
    "\3\35\4\0\1\35\24\0\1\35\5\0\21\35\1\306"+
    "\5\35\4\0\1\35\24\0\1\35\5\0\15\35\1\307"+
    "\11\35\4\0\1\35\24\0\1\35\5\0\4\35\1\310"+
    "\22\35\4\0\1\35\24\0\1\35\5\0\22\35\1\311"+
    "\4\35\4\0\1\35\24\0\1\35\5\0\25\35\1\312"+
    "\1\35\4\0\1\35\24\0\1\35\5\0\15\35\1\313"+
    "\11\35\4\0\1\35\24\0\1\35\5\0\4\35\1\314"+
    "\22\35\4\0\1\35\24\0\1\35\5\0\4\35\1\315"+
    "\22\35\4\0\1\35\24\0\1\35\5\0\10\35\1\316"+
    "\16\35\4\0\1\35\24\0\1\35\5\0\6\35\1\317"+
    "\20\35\4\0\1\35\24\0\1\35\5\0\3\35\1\320"+
    "\23\35\4\0\1\35\24\0\1\35\5\0\22\35\1\321"+
    "\4\35\4\0\1\35\24\0\1\35\5\0\7\35\1\322"+
    "\17\35\4\0\1\35\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7884];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\2\11\2\1\1\11"+
    "\1\1\1\11\2\1\2\11\24\1\5\11\1\1\2\11"+
    "\1\0\1\11\1\0\1\11\2\0\3\11\1\0\1\1"+
    "\1\0\4\11\35\1\2\11\1\1\1\0\41\1\1\11"+
    "\120\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public LinkedList<Errores> listaErrores = new LinkedList<>();    
    
    private Symbol symbol(int type){
		return new Symbol(type, yyline, yycolumn);
	}
	private Symbol symbol(int type, Object value){
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      // sout.println("teto aanlizarrrrrrr: " + yytext());
    yyline = 1;
    yycolumn = 1;
    listaErrores = new LinkedList<>();
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { listaErrores.add(new Errores("LEXICO","El caracter "+
                yytext()+" NO pertenece al lenguaje", yyline, yycolumn));
            }
          // fall through
          case 76: break;
          case 2:
            { 
            }
          // fall through
          case 77: break;
          case 3:
            { return symbol(sym.NOT, yytext());
            }
          // fall through
          case 78: break;
          case 4:
            { return symbol(sym.MOD, yytext());
            }
          // fall through
          case 79: break;
          case 5:
            { return symbol(sym.PAR_OP, yytext());
            }
          // fall through
          case 80: break;
          case 6:
            { return symbol(sym.PAR_CL, yytext());
            }
          // fall through
          case 81: break;
          case 7:
            { return symbol(sym.TIMES, yytext());
            }
          // fall through
          case 82: break;
          case 8:
            { return symbol(sym.PLUS, yytext());
            }
          // fall through
          case 83: break;
          case 9:
            { return symbol(sym.COLON, yytext());
            }
          // fall through
          case 84: break;
          case 10:
            { return symbol(sym.MINUS, yytext());
            }
          // fall through
          case 85: break;
          case 11:
            { return symbol(sym.DOT, yytext());
            }
          // fall through
          case 86: break;
          case 12:
            { return symbol(sym.DIVIDED, yytext());
            }
          // fall through
          case 87: break;
          case 13:
            { return symbol(sym.ENTERO, yytext());
            }
          // fall through
          case 88: break;
          case 14:
            { return symbol(sym.POINTS, yytext());
            }
          // fall through
          case 89: break;
          case 15:
            { return symbol(sym.SEMIC, yytext());
            }
          // fall through
          case 90: break;
          case 16:
            { return symbol(sym.LESS, yytext());
            }
          // fall through
          case 91: break;
          case 17:
            { return symbol(sym.ASSIGNMENT, yytext());
            }
          // fall through
          case 92: break;
          case 18:
            { return symbol(sym.GREATER, yytext());
            }
          // fall through
          case 93: break;
          case 19:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 94: break;
          case 20:
            { return symbol(sym.BRACK_L, yytext());
            }
          // fall through
          case 95: break;
          case 21:
            { return symbol(sym.BRACK_R, yytext());
            }
          // fall through
          case 96: break;
          case 22:
            { return symbol(sym.XOR, yytext());
            }
          // fall through
          case 97: break;
          case 23:
            { return symbol(sym.DEFAULT, yytext());
            }
          // fall through
          case 98: break;
          case 24:
            { return symbol(sym.K_OP, yytext());
            }
          // fall through
          case 99: break;
          case 25:
            { return symbol(sym.K_CL, yytext());
            }
          // fall through
          case 100: break;
          case 26:
            { return symbol(sym.DIFFERENT, yytext());
            }
          // fall through
          case 101: break;
          case 27:
            { String cadenaReconocida = yytext();
                        String cadenaEntregar = cadenaReconocida.substring(1, cadenaReconocida.length() - 1); 
                        return symbol(sym.CADENA, cadenaEntregar );
            }
          // fall through
          case 102: break;
          case 28:
            { return symbol(sym.AND, yytext());
            }
          // fall through
          case 103: break;
          case 29:
            { return symbol(sym.RAISED, yytext());
            }
          // fall through
          case 104: break;
          case 30:
            { return symbol(sym.PLUSPLUS, yytext());
            }
          // fall through
          case 105: break;
          case 31:
            { return symbol(sym.MINUSMINUS, yytext());
            }
          // fall through
          case 106: break;
          case 32:
            { return symbol(sym.L_EQUALS, yytext());
            }
          // fall through
          case 107: break;
          case 33:
            { return symbol(sym.EQUALS, yytext());
            }
          // fall through
          case 108: break;
          case 34:
            { return symbol(sym.ARROW, yytext());
            }
          // fall through
          case 109: break;
          case 35:
            { return symbol(sym.G_EQUALS, yytext());
            }
          // fall through
          case 110: break;
          case 36:
            { return symbol(sym.DO, yytext());
            }
          // fall through
          case 111: break;
          case 37:
            { return symbol(sym.IF, yytext());
            }
          // fall through
          case 112: break;
          case 38:
            { return symbol(sym.OR, yytext());
            }
          // fall through
          case 113: break;
          case 39:
            { String charac = yytext();
                        charac = charac.substring(1, charac.length()-1);
                        return new Symbol(sym.CHARAC, yyline, yycolumn,charac);
            }
          // fall through
          case 114: break;
          case 40:
            { return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 115: break;
          case 41:
            { return symbol(sym.FOR, yytext());
            }
          // fall through
          case 116: break;
          case 42:
            { return symbol(sym.INT, yytext());
            }
          // fall through
          case 117: break;
          case 43:
            { return symbol(sym.NEW, yytext());
            }
          // fall through
          case 118: break;
          case 44:
            { return symbol(sym.VAR, yytext());
            }
          // fall through
          case 119: break;
          case 45:
            { return symbol(sym.BOOLEAN, yytext());
            }
          // fall through
          case 120: break;
          case 46:
            { return symbol(sym.CHAR, yytext());
            }
          // fall through
          case 121: break;
          case 47:
            { return symbol(sym.ELSE, yytext());
            }
          // fall through
          case 122: break;
          case 48:
            { return symbol(sym.FIND, yytext());
            }
          // fall through
          case 123: break;
          case 49:
            { return symbol(sym.LIST, yytext());
            }
          // fall through
          case 124: break;
          case 50:
            { return  symbol(sym.MAIN, yytext());
            }
          // fall through
          case 125: break;
          case 51:
            { return  symbol(sym.THIS, yytext());
            }
          // fall through
          case 126: break;
          case 52:
            { return symbol(sym.BOOL, yytext());
            }
          // fall through
          case 127: break;
          case 53:
            { return symbol(sym.VOID, yytext());
            }
          // fall through
          case 128: break;
          case 54:
            { return symbol(sym.BREAK, yytext());
            }
          // fall through
          case 129: break;
          case 55:
            { return  symbol(sym.CLASS, yytext());
            }
          // fall through
          case 130: break;
          case 56:
            { return symbol(sym.CONST, yytext());
            }
          // fall through
          case 131: break;
          case 57:
            { return symbol(sym.MATCH, yytext());
            }
          // fall through
          case 132: break;
          case 58:
            { return  symbol(sym.PRINT, yytext());
            }
          // fall through
          case 133: break;
          case 59:
            { return symbol(sym.ROUND, yytext());
            }
          // fall through
          case 134: break;
          case 60:
            { return symbol(sym.WHILE, yytext());
            }
          // fall through
          case 135: break;
          case 61:
            { return symbol(sym.APPEND, yytext());
            }
          // fall through
          case 136: break;
          case 62:
            { return symbol(sym.DOUBLE, yytext());
            }
          // fall through
          case 137: break;
          case 63:
            { return symbol(sym.LENGTH, yytext());
            }
          // fall through
          case 138: break;
          case 64:
            { return  symbol(sym.PUBLIC, yytext());
            }
          // fall through
          case 139: break;
          case 65:
            { return symbol(sym.REMOVE, yytext());
            }
          // fall through
          case 140: break;
          case 66:
            { return symbol(sym.RETURN, yytext());
            }
          // fall through
          case 141: break;
          case 67:
            { return symbol(sym.STRING, yytext());
            }
          // fall through
          case 142: break;
          case 68:
            { return symbol(sym.STRUCT, yytext());
            }
          // fall through
          case 143: break;
          case 69:
            { return  symbol(sym.EXTENDS, yytext());
            }
          // fall through
          case 144: break;
          case 70:
            { return  symbol(sym.PRINTLN, yytext());
            }
          // fall through
          case 145: break;
          case 71:
            { return  symbol(sym.PRIVATE, yytext());
            }
          // fall through
          case 146: break;
          case 72:
            { return symbol(sym.CONTINUE, yytext());
            }
          // fall through
          case 147: break;
          case 73:
            { return symbol(sym.TUSTRIN, yytext());
            }
          // fall through
          case 148: break;
          case 74:
            { return  symbol(sym.PROTECTED, yytext());
            }
          // fall through
          case 149: break;
          case 75:
            { return symbol(sym.START_W, yytext());
            }
          // fall through
          case 150: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
